### ISSUE TITLE
ECS Plugin creates multiple revisions for Task Definition

### ISSUE THREAD

**Issue by smohammed09** [jenkinsci/amazon-ecs-plugin#149]
We have few labels configured in jenkins and using ECS plugin. Whenever a slave spins, it creates a new task definition revision  (we are not using 'Task Definition Override') and we have reached 100000 revisions for one of the label which in turn stopped working. We were thinking this plugin is supposed to delete the old revision and create a  new one every time job runs. Can you please shed some light here?

**Comment by resnickdeepfield** [comment]
Does giving a thumbs up count as activity? If not, I am formally bumping this 😅

**Comment by alimeerutech** [comment]
+1

**Comment by arun6445** [comment]
We have the same issue, it would be great if this can be fixed.

**Comment by jeremycarroll** [comment]
A key piece of code is [here](https://github.com/jenkinsci/amazon-ecs-plugin/blame/master/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java#L171), where we see:

> Looks whether the latest task definition matches the desired one. If yes, returns the full TaskDefinition of the existing one.
> If no, register a new task definition with desired parameters and returns the new TaskDefinition.

I inadvertently created a lot of task definitions by having conflict between my production definitions and my development definitions. By using different names for the different definitions I can reduce the conflict and work with rather than against the simple algorithm described above.

**Comment by sglambert** [comment]
@jeremycarroll 

Was your solution just to created multiple task definitions for the different environments? Currently experiencing this same issue with serverless deployments. `sls deploy --stage DEV` will deploy and replace container overrides to dev AND prod.
