### ISSUE TITLE
inheritFrom in scripted pipeline?

### ISSUE THREAD

**Issue by mosaic-nick** [jenkinsci/amazon-ecs-plugin#182]
Hi.

I understand that using inheritFrom is a way of reducing the time Jenkins waits before starting a new container (15 seconds).

Is it possible to do this from a scripted pipeline, rather than declarative?

Thanks,
Nick

**Comment by webratz** [comment]
its not. this is about inheriting config, but it does not reuse agents. so the launch time will not change

**Comment by mosaic-nick** [comment]
I'm not looking to reuse an agent, I'm trying to eliminate the 15 second wait before it creates a new ECS agent. I'd seen somewhere on my travels around Google (actually it is issue #85 on this very repository) that you may be able to do this by using inheritFrom, as it effectively creates a unique "label". But maybe I misunderstood.

**Comment by bradq** [comment]
@mosaic-nick Indeed. If I understand the problem properly, it's not really a universal spawn-time issue but one of Jenkins expecting node reuse. If you're seeking to start a 2nd or 3rd container with an identical `label`, Jenkins tries to assess whether it will have existing capacity...which is of course never useful with normal use of this plugin. inheritFrom does accidentally solve this by using a unique label. I can't speak to whether it's still an issue or whether other workarounds would handle it in a less oblique manner, since we generally use overrides for all contexts. 

I believe the use in scripted syntax is currently broken (or at least I ran into issues that I didn't particularly relish troubleshooting and rolled back to 1.26), but you can follow a proposed fix and pull request with syntax documentation in #179. 

Be sure to also invoke `-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85` if you're seeing particularly long lag times, for roughly the same reasons.

**Comment by mosaic-nick** [comment]
Thanks @bradq, that's been very helpful! Will keep an eye on #179.
